# /*
#  * This file is part of the "dev-in-place" repository located at:
#  * https://github.com/osuvak/dev-in-place
#  * 
#  * Copyright (C) 2017  Onder Suvak
#  * 
#  * For licensing information check the above url.
#  * Please do not remove this header.
#  * */

COPIED_MAKEFILE := $(HOME)/dev_in_place/makefiles/genre/mex/types/ngspice/makefile
TYPE_MK := mex

include $(HOME)/dev_in_place/makefiles/assigner/makefile_assigner.mk